language: ruby
rvm:
- 2.6.3
- 1.9.3
- jruby-19mode
- rbx-2
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
services:
- postgresql
# bundle exec rails db:migrate
# bundle exec rspec
